### ISSUE TITLE
Price Calculation to be called using Mikos LiquidityPool contract i.e. liquidity0 and liquidity1 methods

### ISSUE THREAD

**Issue by Asharp19** [Web3-Ethiopia/DEX#21]
#https://github.com/Web3-Ethiopia/DEX/blob/7a619c3629277c6ea6dffc01f5b1c6b15dcf1618/src/LiqidityPool.sol#L60C1-L72C6

(https://github.com/Web3-Ethiopia/DEX/blob/7182af55ced0de56c23edeba5f8ead493c252605/src/contract/liquidityPoolSwapFunction.sol#L85)

**Comment by kirube1992** [comment]
I update the contract by making the price calculation to be called using mikos liquidityPool 
To change the test contract i think i need to use the hole mikos interface i will push after the interface is done 
or is there other way to work on the test?
